version: "3.7"
services:
  nginx-reverse-proxy:
    build: .
    container_name: nginx-reverse-proxy
    # extra_hosts:
      # - "pihole.proxy:127.0.0.1"
    ports:
      - "443:443"
    expose:
      - "443"
