version: "3.7"
services:
  nginx-reverse-proxy:
    build: .
    container_name: nginx-reverse-proxy
    extra_hosts:
      - "hornsup:192.168.10.10"
    ports:
      - "8401:8401"
      - "8403:8403"
      - "8405:8405"
      - "8406:8406"
      - "8410:8410"
    expose:
      - "8401"
      - "8403"
      - "8405"
      - "8406"
      - "8410"
