apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-reverse-proxy

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

namespace: default

commonLabels:
  app: nginx-reverse-proxy
  version: v1

images:
- name: nginx-reverse-proxy
  newTag: latest

replicas:
- name: nginx-reverse-proxy
  count: 2

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-reverse-proxy
  spec:
    template:
      spec:
        containers:
        - name: nginx-reverse-proxy
          env:
          - name: TZ
            value: "UTC"